# -*- coding: utf-8 -*-
"""Task_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11P_34z6bljet1VAT--QGADv5yEgXuY6_
"""

# chatbot.py

print("🤖 Chatbot: Hi! I'm your simple chatbot. Type 'bye' to exit.")

while True:
    user_input = input("You: ").lower()

    if user_input in ["hi", "hello", "hey"]:
        print("🤖 Chatbot: Hello there! How can I help you today?")

    elif "your name" in user_input:
        print("🤖 Chatbot: I'm a simple chatbot created with Python.")

    elif "how are you" in user_input:
        print("🤖 Chatbot: I'm doing great, thanks for asking! How about you?")

    elif "weather" in user_input:
        print("🤖 Chatbot: I can't check weather yet, but it looks like a good day to code! 🌞")

    elif "bye" in user_input:
        print("🤖 Chatbot: Goodbye! Have a nice day. 👋")
        break

    else:
        print("🤖 Chatbot: Sorry, I didn't understand that. Can you rephrase?")