# -*- coding: utf-8 -*-
"""Task_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bL7eHYlhW-5vMe1YDYpcE04iBpcD3seO
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Superstore_UD_sql.csv", encoding='latin-1')

print(df.head())

print("Rows, Columns:", df.shape)

print(df.info())

print(df.describe())

sales_by_product = df.groupby("Product Name")["Grand total"].sum()
print(sales_by_product)

sales_by_region = df.groupby("Region")["Grand total"].sum()
print(sales_by_region)

df["Order Date"] = pd.to_datetime(df["Order Date"])
monthly_sales = df.groupby(df["Order Date"].dt.to_period("M"))["Grand total"].sum()
print(monthly_sales)

sales_by_product.plot(kind="bar", figsize=(8,5), title="Sales by Product")
plt.ylabel("Total Sales")
plt.show()

sales_by_region.plot(kind="pie", autopct="%1.1f%%", figsize=(6,6), title="Sales by Region")
plt.show()

monthly_sales.plot(kind="line", marker="o", figsize=(10,5), title="Monthly Sales Trend")
plt.ylabel("Total Sales")
plt.show()